### ISSUE TITLE
json/jsonb column support

### ISSUE THREAD

**Issue by jayelkaake** [tomyl/pg-dump-upsert#5]
Love this project!... except can't use it without json and jsonb column support.

My Go is very, very rusty, otherwise I'd submit a PR :p.

**Comment by tomyl** [comment]
Does commit 119ec69da983d210a00ab9e11c39a932ba220ddc work for you?

**Comment by jayelkaake** [comment]
Yes I think so, but for now we already migrated our large database so it might be a while. I'll recommend it to others for sure.

We ended up using AWS's DMS and it was gawdawful. This tool could do a much better job for future migrations since we could do a quick migration for smaller tables then use this to sync up larger tables before flipping to the new DB - thus minimizing downtime.

FYI pg_dump now also has an --upsert option which might be worth checking out (and you can split up the INSERT statements). There was something I didn't like about that though, but I can't remember specifically what it was.

**Comment by tomyl** [comment]
> FYI pg_dump now also has an --upsert option which might be worth checking out (and you can split up the INSERT 
statements).

Oh I missed that, good to know.
